apiVersion: apps/v1
kind: Deployment

metadata:
  name: my-backend-deployment
  namespace: app
  labels:
    component: backend
    app: myapp

spec:
  template:
    metadata:
      name: my-backend-pod
      namespace: app
      labels:
        component: backend
        app: myapp

    spec:
      containers:
        - name: my-backend-container
          image: barpyr/mybackend:latest

          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  key: PGPASSWORD
                  name: my-postgres-secret
          envFrom:
            - configMapRef:
                name: my-app-configmap
  replicas: 1
  selector:
    matchLabels:
      component: backend
      app: myapp