apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-postgres-pv-local
  namespace: app
  labels:
    component: postgres
    type: local
    app: myapp
spec:
  storageClassName: manual
  capacity:
    storage: 20Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
#   https://minikube.sigs.k8s.io/docs/handbook/persistent_volumes/
    path: '/data'