apiVersion: v1
kind: Service

metadata:
  name: my-postgres-service
  namespace: app
  labels:
    component: postgres
    app: myapp

spec:
  type: ClusterIP
  ports:
    - targetPort: 5432
      port: 5432

  selector:
    component: postgres
    app: myapp